### ISSUE TITLE
lack of unit tests

### ISSUE THREAD

**Issue by Padavan** [shartf/AoC2020#2]
There are good places to start write tests like utils.rs or password validation function.

**Comment by shartf** [comment]
Interesting proposal, what level of coverage should we aim for?

**Comment by Vest** [comment]
over 9000.
I can recommend "coverals" project for code coverage.

**Comment by shartf** [comment]
After quick assessment with my team of 1 we have, unfortunately, decided that we do not have resources to cover this code with tests.
